eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://yinzhiyu:yinzhiyu@localhost:8087/eureka
      
data:
  desc: spring-cloud-ex-dev
   
  user:
    username: NaNbcd
    password: NaNbcd